const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
    console.log("🚀 Deploying CloudStorage contract...");

    const CloudStorage = await ethers.getContractFactory("CloudStorage");
    const cloudStorage = await CloudStorage.deploy();
    await cloudStorage.waitForDeployment();

    const address = await cloudStorage.getAddress();
    console.log(`✅ CloudStorage deployed to: ${address}`);

    // Get contract ABI from artifacts
    const artifactPath = path.join(__dirname, "..", "artifacts", "contracts", "CloudStorage.sol", "CloudStorage.json");
    const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));

    // Write config file for frontend
    const configContent = `// Auto-generated by deploy script - DO NOT EDIT MANUALLY
const CONFIG = {
    // Hardhat Local Network
    NETWORK: {
        chainId: '0x7a69',              // 31337 in decimal (Hardhat)
        chainName: 'Hardhat Local',
        rpcUrl: 'http://127.0.0.1:8545',
        blockExplorer: '',
        currency: {
            name: 'CLD',
            symbol: 'CLD',
            decimals: 18
        }
    },

    // Server Configuration
    SERVER: {
        url: 'http://localhost:3000'
    },

    // Smart Contract
    CONTRACT: {
        address: '${address}',
        abi: ${JSON.stringify(artifact.abi, null, 8)}
    }
};
`;

    const configPath = path.join(__dirname, "..", "js", "config.js");
    fs.writeFileSync(configPath, configContent);
    console.log(`📝 Config written to: ${configPath}`);
    console.log("");
    console.log("🎉 Deployment complete! You can now start the server:");
    console.log("   node server.js");
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error("❌ Deployment failed:", error);
        process.exit(1);
    });
